######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 17 03:04:40 2011
######################################################################

TEMPLATE = app
TARGET = badcat
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

# Input
SOURCES += badcat.cpp
